server {
    # dostupné na adrese localhost na portu 80 (nešifrované; HTTP) na pc hostitele
    listen 80;
    server_name localhost;

    location / {
        # Nginx se nejprve pokusí najít reálný statický soubor na disku (produkce); standardní produkční root Nginxu
        root /usr/share/nginx/html;
        index index.html;

        # pokud tam soubor najde (v produkci ano), pošle ho
        # pokud ho tam nenajde (vývojový režim, složka je prázdná), tak se aktivuje @vite_fallback a požadavek se přehodí na Vite
        try_files $uri $uri/ @vite_fallback;
    }

    # spustí se jen při vývoji; produkci řeší Nginx
    # FRONTEND (React); Vite server; odchytává web komunikace
    location @vite_fallback {
        # když uživ. chce nějakou stránku (kromě "/api"), tak ten požadavek přepošleme skrz interní síť Dockeru na kontejner s názvem "frontend" na port 5173
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;

        # při změně si Vite otevře perma duplex kanál do prohlížeče a provede změnu bez reloadu (Hot-Reload a WebSocket; klient chce přejít z HTTP na WebSocket); tímto to nebude blokováno Nginxem
        # Při změně souboru to zjistí Vite server frontendu, ten má přes Nginx do prohlížeče trvalý Websocket, pošle data a React u klienta to změní  bez reloadu
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # backend API; Symfony server; požadavky začínající na "/api" se pošlou na kontejner backendu
    location /api {
        # Symfony standardně směruje vše přes soubor index.php ve složce public
        root /var/www/html/public;

        # cokoli přijde na /api, pošli na /index.php
        # pomocí regexu, cokoliv je za "/api/" (tedy třeba "orders") veme, a interně to v paměti přepíše na adresu "/index.php/orders“
        rewrite ^/api/(.*)$ /index.php/$1 last;
    }

    # zpracování index.php přes produkční FastCGI (FPM port 9000); chytí přepsaný požadavek (obsahuje "index.php")
    location ~ ^/index\.php(/|$) {
        root /var/www/html/public;

        # Nginx komunikuje přímo s PHP-FPM (neposílá HTTP požadavek) bez nutnosti php -S serveru; vezme data, převede je do bin. protokolu FastCGI a pošle je na port 9000 kontejneru backend, tam je PHP-FPM
        # PHP-FPM vezme volné vlákno (worker), podívá se na parametr SCRIPT_FILENAME (zjistí, že má spustit soubor /var/www/html/public/index.php, což je vstupní brána Symfony),
        # předá mu parametr "orders"; Symfony zpracuje byznys logiku, vrátí JSON text, PHP-FPM ho předá zpět Nginxu a Nginx ho zabalí do HTTP odpovědi a pošle do Reactu
        fastcgi_pass backend:9000;

        # rozdělení adresy na 2 části; první "/index.php" (soubor, který se má spustit; pro každý dotaz se spouští Symfony nově), druhá "/orders" (parametr, podle kterého Symfony interně pozná, do kterého kontroleru jít)
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        # načte ze systému standardní sadu Linuxových konfiguračních tabulek (jak se překládá HTTP port, request metoda atd.)
        include fastcgi_params;

        # propojení cest uvnitř kontejneru
        # příkaz pro PHP-FPM kontejner; ignoruje všechno ostatní, otevře disk uvnitř svého kontejneru a natvrdo spusťí tento PHP skript na této cestě; což spustí Symfony Kernel, přečte param a vykoná kód, pak se celý ukončí
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;

        # předání IP adres; Symfony komunikuje s Nginx, tedy z pohledu Symfony by vše šlo z ip adresy kontejneru Nginx
        # nginx dosadí skutečnou adresu klienta do požadavku (Symfony to může použít pro logování, ...)
        fastcgi_param REMOTE_ADDR $remote_addr;
        fastcgi_param HTTP_X_REAL_IP $remote_addr;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
    }
}
